version: "3"

services:
  front:
    container_name: front
    image: node:16-alpine
    working_dir: /app
    command: yarn start
    volumes:
      - "./front:/app"
    ports:
      - "4000:4000"
    depends_on:
      - back

  back:
    build:
      context: ./back
    image: node-file-compression
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-file-compression
    ports:
      - '3001:3001'
    depends_on:
      - mongodb-file-compression
    volumes:
      - ./back:/usr/src/node-app
    networks:
      - node-network
    env_file:
      ./back/.env

  mongodb-file-compression:
    image: mongo:latest
    container_name: mongodb-file-compression
    hostname: mongodb
    volumes:
        - ./back/.docker/mongodb/mongod.conf:/etc/mongod.conf
        - ./back/.docker/mongodb/data/db/:/data/db/
        - ./back/.docker/mongodb:/home/mongodb
        - ./back/script:/docker-entrypoint-initdb.d/
    ports:
        - "27017:27017"
    networks:
      - node-network
    env_file:
      ./back/.env

  # back:
  #   container_name: back
  #   image: node:16-alpine
  #   working_dir: /app
  #   command: yarn start
  #   volumes:
  #     - "./back:/app"
  #   depends_on:
  #     - image_compressor

  # image_compressor:
  #   container_name: image_compressor
  #   image: mcr.microsoft.com/dotnet/sdk
  #   working_dir: /app
  #   volumes:
  #     - "./image_compressor:/app"

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge