version: "3"

services:
  front:
    container_name: front
    image: node:16-alpine
    working_dir: /app
    command: yarn start
    volumes:
      - "./front:/app"
    ports:
      - "4000:4000"
    depends_on:
      - back

  # back:
  #   container_name: back
  #   image: node:16-alpine
  #   working_dir: /app
  #   command: yarn start
  #   volumes:
  #     - "./back:/app"
  #   depends_on:
  #     - image_compressor

  # image_compressor:
  #   container_name: image_compressor
  #   image: mcr.microsoft.com/dotnet/sdk
  #   working_dir: /app
  #   volumes:
  #     - "./image_compressor:/app"
