version: "3"

services:
  front:
    container_name: front
    image: node:16-alpine
    working_dir: /app
    command: yarn start
    volumes:
      - "./front:/app"
    ports:
      - "3000:3000"
    depends_on:
      - back

  back:
    build:
      context: ./back
    image: node-file-compression
    ports:
      - '3001:3001'
    depends_on:
      - imagecompressor
      - mongodb
    volumes:
      - ./back:/usr/src/node-app
    networks:
      - node-network
    env_file:
      ./back/.env

  imagecompressor:
    build:
      context: ./image-compressor
      dockerfile: ./Dockerfile
    image: ${DOCKER_REGISTRY-}image-compressor
    networks:
      - node-network
    ports:
      - '80:80'
    volumes:
      - ./image-compressor:/src

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    volumes:
        - ./back/.docker/mongodb/mongod.conf:/etc/mongod.conf
        - ./back/.docker/mongodb/data/db/:/data/db/
        - ./back/.docker/mongodb:/home/mongodb
        - ./back/script:/docker-entrypoint-initdb.d/
    ports:
        - "27017:27017"
    networks:
      - node-network
    env_file:
      ./back/.env

networks:
  node-network:
    driver: bridge