version: '3'

services:
  node-file-compression:
    build: .
    image: node-file-compression
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-file-compression
    ports:
      - '3000:3000'
    depends_on:
      - mongodb-file-compression
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network
    env_file:
      - ./back/.env

  mongodb-file-compression:
    image: mongo:latest
    container_name: mongodb-file-compression
    hostname: mongodb
    volumes:
        - ./back/.docker/mongodb/mongod.conf:/etc/mongod.conf
        - ./back/.docker/mongodb/data/db/:/data/db/
        - ./back/.docker/mongodb:/home/mongodb
        - ./back/script:/docker-entrypoint-initdb.d/
    env_file:
      ./back/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
        - "27017:27017"
    networks:
      - node-network


volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
